### ISSUE TITLE
Custom form problems

### ISSUE THREAD

**Issue by PlkMarudny** [x0k/svelte-jsonschema-form#31]
I would like to use a form without a 'submit' button. According to documentation I simply copied the code removing the `<SubmitButton />` component, but when used like:

```
<SimpleForm {form} />
```
it obviously renders the submit button, which is part of  `SimpleForm.svelte` .

Using:
```
<CustomForm {form} />
```
instead throws:
```
Uncaught TypeError: Cannot read properties of undefined (reading '$ref')

	in +page.svelte
	in Pane.svelte
	in Splitpanes.svelte
	in Pane.svelte
	in Splitpanes.svelte
	in +layout.svelte
	in +layout.svelte
	in root.svelte

    at resolveAllReferences (resolve.js:25:17)
    at resolveReference2 (resolve.js:78:28)
    at resolveSchema2 (resolve.js:242:28)
    at retrieveSchemaInternal (resolve.js:88:29)
    at retrieveSchema2 (resolve.js:21:12)
    at getDefaultFormState2 (default-state.js:43:20)
    at DefaultFormMerger.mergeFormDataAndSchemaDefaults (merger.js:13:16)
    at createForm (use-form.svelte.js:12:31)
    at useForm (use-form.svelte.js:208:24)
    at useCustomForm (src/lib/components/forms/custom-form.js?t=1731578022506:9:12)TypeError: Cannot read properties of undefined (reading '$ref')
    at resolveAllReferences (resolve.js:25:17)
    at resolveReference2 (resolve.js:78:28)
    at resolveSchema2 (resolve.js:242:28)
    at retrieveSchemaInternal (resolve.js:88:29)
    at retrieveSchema2 (resolve.js:21:12)
    at getDefaultFormState2 (default-state.js:43:20)
    at DefaultFormMerger.mergeFormDataAndSchemaDefaults (merger.js:13:16)
    at createForm (use-form.svelte.js:12:31)
    at useForm (use-form.svelte.js:208:24)
    at useCustomForm (custom-form.js:9:12)
```
Where did I make a mistake?

**Comment by x0k** [comment]
Looks like there is a problem with calculating defaults for your json schema.
Can you share you schema?

**Comment by PlkMarudny** [comment]
Here is the schema:

```
const schema = {
		type: 'object',
		properties: {
			title: {
				type: 'string'
			},
			content: {
				type: 'string'
			}
		}
	};
```
and uiSchema:
```
const uiSchema = {
		'ui:globalOptions': {
			hideTitle: true,
			input: {
				spellcheck: false,
				autocomplete: 'off'
			}
		},
		submitButton: {
			disabled: true
		},
		content: {
			'ui:widget': 'textarea'
		}
	};
```

**Comment by x0k** [comment]
I think the schema is not passed to the `useCustomForm` hook.

Maybe this example will help https://github.com/x0k/sjsf-examples/blob/00c9106addb1e3494885d16949e94495d087bc9b/src/routes/my-simple-form/%2Bpage.svelte

**Comment by PlkMarudny** [comment]
This works, thank you very much. In fact, this example is perfect for my use case. Great library.
